### ISSUE TITLE
Carthage Compatibility

### ISSUE THREAD

**Issue by Steven0351** [gohypergiant/IAPKit#9]
It would be nice to be able to pull this in as a Carthage dependency instead of as a git submodule. The iOS scheme is already shared, so all that should really be necessary is to tag releases.

**Comment by bclubb** [comment]
Isn't this possible using the branch instead of release? I know it's not optimal, but a solution for Carthage users.

`github "blackpixel/IAPKit" "master"`

**Comment by ThuggishNuggets** [comment]
Hey @Steven0351, I know you're just cleaning this up, but can you get someone to remove me from the Hypergiant Org? I haven't worked there for years now. I previously tried sending an email to someone about it but it was never resolved and I still have access to all of your repos.

**Comment by hernanpelassini** [comment]
I have Never worked for Hypergiant. I would also appreciate being removed
from whatever decided to include me in this thread.
Thanks.

**Comment by Steven0351** [comment]
@ThuggishNuggets @hernanpelassini I don't work here, I was just tired of seeing this in my created issues and it was obviously never going to get addressed, so I closed it.

**Comment by Steven0351** [comment]
Also, you can remove yourself from any org https://github.com/settings/organizations

**Comment by ThuggishNuggets** [comment]
@Steven0351 ah sounds like you're in the same boat then. I removed myself a while back but somehow I still have access to everything. 🤦🏻
